modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"

[[mods]]
modId="fumi_neoforge"
version="${file.jarVersion}"
displayName="Fumi NeoForge"
authors="Fumi"
description="Bridges Minecraft chat with other platforms through NATS."
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.fumi_neoforge]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.fumi_neoforge]]
modId="minecraft"
type="required"
versionRange="[26.1,26.4)"
ordering="NONE"
side="BOTH"
