plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
}

configurations {
    library
    implementation.extendsFrom library
}

base {
    archivesName = "FumiFabric"
}
version = project.mod_version

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation project(":common")

    library "io.nats:jnats:2.25.1"
}

jar {
    from project(":common").sourceSets.main.output.classesDirs

    from {
        configurations.library.collect { it.isDirectory() ? it : zipTree(it) }
    }

    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.RSA'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/maven/**'
    exclude 'module-info.class'

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jar') {
    archiveFileName = "${base.archivesName.get()}-${project.minecraft_version}-${project.version}.jar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}
